"""Pins the CCA-F Bins & Lists deck.

Generated by BTE_APP_backend/scripts/gen_cca_bins_and_lists.py from
~/Documents/learning/claude-arc-exam/reference/list-membership.html.

Like the sibling deck tests, this reads the JSON artifact only — never the
generator — so the file that actually gets imported is the thing under test.
"""

import json
import os
import re
from collections import Counter

DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "data")
DATA_PATH = os.path.join(DATA_DIR, "cca_bins_and_lists.json")

BINS = {
    "A - API · BODY": 7,
    "B - MCP · PROCESS": 5,
    "C - Claude Code · FILE": 12,
    "D - Agent SDK · PROGRAM": 2,
    "E - No surface": 4,
}
# Members that legitimately sit in two lists get a "which two?" pair card in its
# own facet bucket rather than being forced into one bin.
COLLISION_BIN = "Z - collision (two bins)"
COLLISION_LIST = "z - collision (two lists)"

DIRECTIONS = {
    "1 - Roster (list to members)": 39,
    "2 - Count": 29,
    "3 - Term to list": 116,
    "4 - Term to bin": 116,
    "5 - Bin and its lists": 40,
}
TOTAL = sum(DIRECTIONS.values())

SIBLING_DECKS = (
    "cca_scenarios.json",
    "cca_field_delta.json",
    "cca_field_delta2.json",
    "cca_cheatsheet_facts.json",
    "arc_foundations.json",
)


def load(name="cca_bins_and_lists.json"):
    with open(os.path.join(DATA_DIR, name), encoding="utf-8") as fh:
        return json.load(fh)


def _normalize(text):
    return re.sub(r"\W+", " ", text).strip().lower()


# --------------------------------------------------------------- structure --

def test_deck_header():
    deck = load()
    assert deck["deck_name"] == "CCA-F Bins & Lists"
    assert deck["match_strategy"] == "multi_choice"
    assert deck["render_config"] == {"fields": ["bin", "direction", "list"]}


def test_total_card_count():
    assert len(load()["cards"]) == TOTAL


def test_source_and_four_distinct_choices():
    for card in load()["cards"]:
        meta = card["metadata"]
        assert meta["source"] == "cca_bins_and_lists"
        choices = meta["choices"]
        assert isinstance(choices, list) and len(choices) == 4
        assert len(set(choices)) == 4
        assert all(isinstance(c, str) and c.strip() for c in choices)
        assert card["answer"] in choices


def test_numbers_unique_and_complete():
    numbers = [c["metadata"]["number"] for c in load()["cards"]]
    assert sorted(numbers) == list(range(1, TOTAL + 1))


def test_every_card_carries_the_three_facet_keys():
    # render_config promises bin/direction/list; an absent key silently drops
    # the card out of a filtered session instead of erroring.
    for card in load()["cards"]:
        meta = card["metadata"]
        for key in ("bin", "direction", "list", "key", "explanation"):
            assert isinstance(meta.get(key), str) and meta[key].strip(), meta


def test_direction_distribution():
    assert Counter(c["metadata"]["direction"] for c in load()["cards"]) == DIRECTIONS


def test_bin_inventory():
    cards = load()["cards"]
    assert set(c["metadata"]["bin"] for c in cards) == set(BINS) | {COLLISION_BIN}

    # One "how many lists on this surface" card per bin, and its answer must
    # equal the number of distinct lists actually carded in that bin.
    counts = {}
    for card in cards:
        if card["prompt"].startswith("How many closed lists"):
            for label in BINS:
                if label in card["prompt"]:
                    counts[label] = int(card["answer"])
    assert counts == BINS

    for label, expected in BINS.items():
        listed = set(
            c["metadata"]["list"] for c in cards
            if c["metadata"]["bin"] == label and c["metadata"]["list"] != "(whole bin)"
        )
        assert len(listed) == expected, (label, sorted(listed))


def test_counts_agree_with_their_own_rosters():
    """A count card and its roster card must never disagree."""
    cards = load()["cards"]
    rosters = {
        c["metadata"]["list"]: c["answer"].split(" · ")
        for c in cards if c["metadata"]["direction"].startswith("1 -")
    }
    seen = 0
    for card in cards:
        if not card["metadata"]["direction"].startswith("2 -"):
            continue
        name = card["metadata"]["list"]
        assert int(card["answer"]) == len(rosters[name]), name
        seen += 1
    assert seen == DIRECTIONS["2 - Count"]


# ------------------------------------------------- the deck's core promise --

def _atoms(cards):
    """Every string the deck attests as real, gathered from correct answers only."""
    atoms = set()
    for card in cards:
        meta = card["metadata"]
        atoms.add(meta["bin"])
        atoms.add(meta["list"])
        direction, answer = meta["direction"], card["answer"]
        if direction.startswith(("3 -", "4 -")):
            # list names / bin labels — never split, they contain " · "
            atoms.update(answer.split(" + "))
        elif direction.startswith("2 -"):
            atoms.add(answer)
        else:
            atoms.update(answer.split(" · "))
    return atoms


def _decompose(option, atoms):
    """Yield the parts of an option that are not attested atoms."""
    if option in atoms:
        return
    for half in option.split(" + "):
        if half in atoms:
            continue
        for atom in half.split(" · "):
            if atom not in atoms:
                yield atom


def test_no_fabricated_strings():
    """The authoring rule, enforced.

    Every option on every card must be built from strings this deck vouches for
    as real somewhere else. A wrong option is a real member of the wrong list —
    never an invented near-miss. Veto cards using true non-members are a
    deliberate follow-up; if one lands here without its own allowance, this
    test is what catches it.
    """
    cards = load()["cards"]
    atoms = _atoms(cards)
    bad = []
    for card in cards:
        for option in card["metadata"]["choices"]:
            for atom in _decompose(option, atoms):
                bad.append((card["metadata"]["key"], atom))
    assert not bad, "fabricated strings: %s" % bad[:10]


def test_collision_members_get_a_pair_card():
    """A string in two lists is unanswerable as 'which list?' — it must pair."""
    cards = load()["cards"]
    pair_cards = [c for c in cards if c["metadata"]["bin"] == COLLISION_BIN]
    assert pair_cards, "expected the auto / deny / allow collisions to be carded"
    for card in pair_cards:
        assert card["metadata"]["list"] == COLLISION_LIST
        assert " + " in card["answer"]
        assert all(" + " in choice for choice in card["metadata"]["choices"])
    # `auto` is the collision the whole source sheet is organised around.
    assert any("`auto`" in c["prompt"] for c in pair_cards)


# ---------------------------------------------------------------- anti-tell --

def test_prompts_distinct():
    prompts = [_normalize(c["prompt"]) for c in load()["cards"]]
    assert len(set(prompts)) == len(prompts)


def test_answer_position_is_not_a_tell():
    slots = Counter(
        c["metadata"]["choices"].index(c["answer"]) for c in load()["cards"]
    )
    assert set(slots) == {0, 1, 2, 3}
    assert min(slots.values()) >= TOTAL / 8, "position spread skewed: %s" % dict(slots)


def test_answer_length_is_not_a_tell():
    """Only a STRICTLY longest answer leaks.

    This deck deliberately fields options that tie on length — permutations of
    an ordered roster, and count cards whose options are all single digits.
    A tie carries no signal a test-taker could act on, so the sibling decks'
    ties-included measure would flag ~24% of cards for a tell that does not
    exist. Strictly-longest is the honest measure here.
    """
    cards = load()["cards"]
    strictly_longest = sum(
        1 for c in cards
        if all(len(c["answer"]) > len(x)
               for x in c["metadata"]["choices"] if x != c["answer"])
    )
    assert strictly_longest <= len(cards) / 4, (
        "longest-option heuristic scores %d/%d" % (strictly_longest, len(cards))
    )


def test_no_prompt_overlap_with_existing_decks():
    existing = set()
    for name in SIBLING_DECKS:
        for card in load(name)["cards"]:
            existing.add(_normalize(card["prompt"].rpartition("\n\n")[2]))
    for card in load()["cards"]:
        assert _normalize(card["prompt"]) not in existing, card["prompt"]
